version: '3.9'

services:
  scheduler-react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173" #vite port for app
      - "24678:24678" # hmr port
    environment:
      - NODE_ENV=development
    stdin_open: true 
    tty: true 
